name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS with SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker pull roger375/simple-app:01
          docker stop simple-app || true && docker rm simple-app || true
          docker run -d -p 8080:80 --name simple-app roger375/simple-app:01
